# 넘파이(Numpy) 배열 프로그래밍

### 1.넘파이 배열
### Array(배열) : '동일한 자료형'을 순서대로 저장하여 처리하는 자료구조
### python 자료형 : List, Tuple, set, Dict
#### List[](가변 길이 배열), Tuple()-변경불가(default type), set{}집합-중복값 허용하지않음, Dict{}-key(인덱스의의미):value(리스트, 튜플, 또 다른 딕셔너리, 집합이 올 수 있다.)
### Numpy 자료구조 :  다차원 '배열' 자료구조 클래스 'ndarray' <- 벡터, 행열, 선형개수, 통계분석, C언어 기바능로 만들어짐, numpy는 반복문을 사용하지 않으나, 반복 할 수 있다. 


In [67]:
a = [1, 2, 3, 4, 5]
b = [1, 2, 3, 4, 5]
c = []    #비어있는 리스트 객체
# for 개별변수 in 집합변수(주어진 횟수동안 반복)
#range의 하나의 값 시작이 0이고 a는 5니 range의 5는 다섯개라는 의미
#range(5) : 0,1,2,3,4
#c라는 객체에 append(추가해라)
for i in range(len(a)):
    c.append(a[i]*b[i])
    
print(c)


#반복문이라는 것은 속도를 빠르게 하는 것은 아니다. 속도가 느리다.
#반복문을 사용하지 않고 numpy를 통해서 반복할 수 있다.

[1, 4, 9, 16, 25]


In [72]:
c = a * b
c 
# 이게 실행이 된다는 의미는 반복문을 넣지 않아도 된다.
# 다시 numpy page로 가보자. #이게 에러가 나기 때문에 numpy를 써야한다.

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
#넘파이를 작업하려면 넘파이를 import 해야해

###2. 넘파이 패키지 임포트

In [73]:
import numpy as np #as는 별칭

In [70]:
#checking numpy library version
np.__version__

'1.20.3'

In [71]:
x = np.array(a) #파이썬의 기본 자료형을 들고와서 쓸 수 있다. array에 넣어서 numpy
y = np.array(b)
x * y

array([ 1,  4,  9, 16, 25])

### 수업에 사용할 함수 정의

In [77]:
def pprint(arr):
    print('type : {}'.format(type(arr)))
    print('shape: {}, dimension:{}, dtype:{}'.format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n", arr)

#### 파이썬 1차원 배열(list)로 Numpy 배열 생성하는 방법

In [78]:
pprint(a)
#결과 중
#shape:(3,)
#행만 나오니 1차원, dimension:1, dtype:int32

type : <class 'list'>


AttributeError: 'list' object has no attribute 'shape'

In [79]:
import teacher

In [80]:
from teacher import *

### 파이썬 2차원 배열로  Numpy 배열 생성, 원소 데이터 타입 지정

In [81]:
arr = [[1,2,3],[4,5,6]] #2차원#행이2개#열이3개
arr2 = [(1,2,3), (4,5,6)]
b = np.array(arr, dtype = float)

In [83]:
pprint(b)

type : <class 'numpy.ndarray'>
shape: (2, 3), dimension:2, dtype:float64
Array's Data : 
 [[1. 2. 3.]
 [4. 5. 6.]]


#### 파이썬 3차원 배열로  Numpy 배열 생성, 원소 데이터 타입 지정

In [84]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[3, 2, 1], [4, 5, 6]]], 
               dtype = float)

In [85]:
pprint(arr)

type : <class 'numpy.ndarray'>
shape: (2, 2, 3), dimension:3, dtype:float64
Array's Data : 
 [[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]


#### np.zeros(shape, dtype=floar, order='C')
- 지정 된 shape의 배열을 생성하고, 모든 요소를 0으로 초기화

In [86]:
a = np.zeros((3,4))
pprint(a)

type : <class 'numpy.ndarray'>
shape: (3, 4), dimension:2, dtype:float64
Array's Data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### np.ones(shape,dtype=None, order='C')
- 지정된 shape의 배열을 생성하고, 모든 요소를 1로 초기화

In [87]:
a = np.ones((2, 3, 4), dtype = np.int16)
pprint(a)

type : <class 'numpy.ndarray'>
shape: (2, 3, 4), dimension:3, dtype:int16
Array's Data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


####np.full(shape, fill_value, dtype=None, order='C')
- 지정된 shape의 배열을 생성하고, 모든 요소를 fill_value값으로 초기화

In [88]:
#2행2열짜리 만들고7로 채우고 싶어
a = np.full((2,2), 7)
pprint(a)

type : <class 'numpy.ndarray'>
shape: (2, 2), dimension:2, dtype:int32
Array's Data : 
 [[7 7]
 [7 7]]


#### np.eye(N, M=None, k=0, dtype=float)
- (N, N) shape의 단위 행렬을 생성
- 단위 행렬 : 대각선으로 같은 숫자를 채우는 것

In [89]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### np.empty(shape, dtype=float, order='C')
- 지정된 shape의 배열 생성
- 요소의 초기화과정이 없고, 기존 메모리 값을 그대로 사용
- 배열의 생성 비용이 가장 저렴하고 빠르게 처리하기 위해

In [90]:
a = np.empty((4, 2))
pprint(a)

type : <class 'numpy.ndarray'>
shape: (4, 2), dimension:2, dtype:float64
Array's Data : 
 [[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.19359580e-321]
 [9.34602320e-307 1.42410974e-306]]


### like계열의 함수
- like의 뜻 ~처럼, ~와 같은
- 지정된 배열과shape이 같은 배열을 만드는 함수
- np.zeros_like(0으로 채워라, like는 기존에 만든 배열)
- np.ones_like
- np.full_like
- np.empty_like

In [91]:
a = np.array([[1,2,3], [4,5,6]])
b = np.ones_like(a)
pprint(b)

type : <class 'numpy.ndarray'>
shape: (2, 3), dimension:2, dtype:int32
Array's Data : 
 [[1 1 1]
 [1 1 1]]


#### 난수 발생과 카운팅
- 난수(random number) : 파이썬을 이용하여 데이터를 무작위로 섞거나 임의의 수
- 시드(seed) : 주고싶은 정수값을 주면 된다. 0이거나 0보다 큰 정수

In [92]:
#seed 설정
np.random.seed(0)

In [93]:
#rand : 0~1사이의 난수 발생 함수
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [94]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [95]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [96]:
np.random.seed(0)

In [97]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [98]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

### 데이터의 순서 변경 : shuffle

In [99]:
x = np.arange(10) #0부터9가 순차적으로 만들어 진다.
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.random.shuffle(x)
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

### 데이터 샘플링(표본추출) : choice
- np.random.choice(샘플링할데이터, size=None, replace=True, p(확률)=None)
- 데이터 집합에서 무작위로 데이터를 선택해서 추출하는것
- data: 원본 데이터, arrange(data)
- size: 샘플 숫자
- replace: True면 한 번 선택한 데이터를 다시 선택가능
- p: 각 데이터가 선택 될 수 있는 확률
- shuffle과 유사

In [101]:
np.random.choice(5, 5, replace = False) #shuffle 명령과 유사

array([0, 4, 2, 1, 3])

In [102]:
np.random.choice(5,3, replace=False)

array([4, 2, 3])

In [103]:
np.random.choice(5, 10) #replace=True

array([0, 2, 4, 3, 3, 2, 4, 2, 0, 0])

In [104]:
np.random.choice(5, 10, p = [0.1, 0, 0.3, 0.6, 0]) 

array([2, 2, 2, 2, 3, 3, 3, 3, 0, 3])

#### 난수 생성
- rand : 0부터 1사이의 균일분포
- randn : 표준 정규 분포
- randint : 균일 분포의 정수 난수
- randint(low, high=None, size(발생할 난수의 숫자))

In [14]:
np.random.randint(10, size=10) #10보다 작은 숫자 열개

NameError: name 'np' is not defined

In [ ]:
np.random.randint(10, 20, size=10) #10이상 20미만 값 10개

In [ ]:
np.random.randint(10, 20, size=(3, 5)) #size에 튜플#3행5열짜리

#### 정수 데이터 카운팅
-unique

In [15]:
np.unique([11,11,2,2,34,34])

NameError: name 'np' is not defined

In [ ]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts = True)

In [ ]:
index

In [ ]:
count

#### 데이터 생성 함수
- Numpy는 주어진 조건으로 데이터를 생성한 후, 배열을 만드는 데이터 생성함수 제공
- np.linspace :(start, stop, num=50): 요소의 개수를 기준으로 해서 균등한 간격으로 생성 된 값을 배열로 만듦
- np.arange(start, stop, step)
- np.logspace : 로그값을 만들어 내라

In [16]:
a = np.linspace(0, 1, 5) #0~1사이의 범위에서 5개의 숫자를 만들어 내라 그 간격의 균일해야해
pprint(a)

NameError: name 'np' is not defined

In [ ]:
import matplotlib.pyplot as plt
plt.plot(a, 'o')
plt.show

In [ ]:
a = np.logspace(0.1, 1, num=20)
pprint(a)
plt.show()

#### 난수 기반 배열 생성
- np.random.normal(loc = 0.0, scale=1.0, size)
- np.random.normal(정규분포평균, 표준편차, size)

- np.random.rand ....
- np.random.random
- np.random.rand()
- np.random.randn()
- np.random.randint()

In [17]:
mean = 0
std = 1
a = np.random.normal(mean, std, (2, 3))
pprint(a)

NameError: name 'np' is not defined

In [ ]:
data = np.random.normal(0, 1, 10000)
plt.hist(data, bins=100)
plt.show()

In [ ]:
data = np.random.rand(10000)
plt.hist(data, bins=10) #histogram빈도표
plt.show()

In [18]:
data = np.random.randn(10000)
plt.hist(data, bins=10) 
plt.show()

NameError: name 'np' is not defined

In [ ]:
data = np.random.randint(-100, 100, 10000)
plt.hist(data, bins=10) 
plt.show()

#### Numpy 입출력
##### 바이너리(Binary)
- np.save() : Numpy 배열 객체 1개를 파일에 저장(확장자 : npy)
- np.savez(): Numpy 배열 객체 복수개를 파일에 저장(확장자 : npz)
- np.load() : Numpy 배열 저장 파일로부터 객체 로딩
##### 텍스트(text)
- np.loadtxt() : 텍스트 파일로부터 배열 로딩
- np.savetxt() : 텍스트 파일로에 Numpy 배열 객체 저장

In [19]:
a = np.random.randint(0, 10, (2,3))
b = np.random.randint(0, 10, (2,3))

pprint(a)
pprint(b)

NameError: name 'np' is not defined

1개 배열 파일에 저장

In [20]:
np.save('my_array1', a) #a라는 객체를 myarray1로 저장하겠다.

NameError: name 'np' is not defined

In [ ]:
!ls -al my_array1

In [ ]:
!dir

In [ ]:
np.savez('my_array2', a, b) #a와b 두개의 파일을 저장하겠다.

In [ ]:
np.load('my_array1.npy') #확장자를 담아야 한다.y도 있고 z도 있으니깐

In [21]:
x = np.load('my_array2.npz')

NameError: name 'np' is not defined

In [ ]:
x.files #어떤 배열 객체 파일을 갖고 있는지 보여줘

In [ ]:
x['arr_0']

In [ ]:
x['arr_1']

### 4.Numpy data type

np.int64 #64비트 기반의 정수
np.float32 Standard double-precision floating point
np.complex Complex numbers represented by 128 floats
np.bool Boolean type storing TRUE and FALSE values
np.object Python object type
np.string_Fixed-length string type # 고정 길이 문자타입
np.unicode_  #유니코드 형태로 저장해라#한글은3바이트

### inspecting: 배열 상태 검사
-a.shape 차원을 알려줌 튜플로 나타냄 
-len(a) 배열의 길이 
-b.ndim n차원의 개수 
-e.size 배열의 요소의 수elements 
-b.dtype 
-b.dtype.name  
-b.astype(int) 배열의 타입을 변환해라

In [22]:
arr = np.random.random((5, 2, 3))

NameError: name 'np' is not defined

In [ ]:
# 배열 타입 : 객체 타입
type(arr)

In [ ]:
# 배열의 shape확인
arr.shape

In [23]:
#배열의 길이 확인
len(arr)

2

In [24]:
#배열의 차원 수
arr.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
#배열의 요소 수 : shape(k면, m행, n렬) = k *m * n
arr.size


In [ ]:
# 배열의 데이터 타입
arr.dtype

In [ ]:
arr.dtype.name

In [ ]:
arr.astype(np.int)

In [ ]:
arr.astype(np.float64)

In [ ]:
#R에서 str과 비슷
np.info(np.ndarray.dtype)

### 도움말

In [25]:
np.info(np.ndarray.dtype)

NameError: name 'np' is not defined

#### 배열 연산
- arrange(1, 10) : 1부터 10미만의 범위에서 1씩 증가하는 배열 생성

In [26]:
a = np.arange(1, 10).reshape(3,3)
pprint(a)

NameError: name 'np' is not defined

In [ ]:
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b) 

In [ ]:
a + b

In [ ]:
a - b

In [27]:
np.add(a, b)

NameError: name 'np' is not defined

In [ ]:
np.subtract(a, b)

In [ ]:
a / b

In [ ]:
np.divide(a,b)

In [ ]:
np.multiply(a, b)

In [28]:
#지수
np.exp(b)

NameError: name 'np' is not defined

In [ ]:
#제곱근
np.sqrt(a)

In [ ]:
np.sin(a)

In [ ]:
np.cos(a)

In [29]:
np.tan(a)

NameError: name 'np' is not defined

In [ ]:
np.log(a)

In [ ]:
#내적 = 행렬곱
np.dot(a, b)

In [ ]:
a == b

In [ ]:
a > b

In [30]:
#배열 전체를 비교
np.array_equal(a, b)

NameError: name 'np' is not defined

In [ ]:
#넘파이는 축을 기준으로 계산한다.

#### 집계함수(Aggregate Function)
- axis(축)을 기준으로 계산한다.
- axis = None(지정하지않음), 0, 1
- axis = None : 전체행렬을 하나의 배열로 간주
- axis = 0 : 열끼리 묶어서 연산 수행
- axis = 1 : 행끼리 묶어서 연산 수행

In [31]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

NameError: name 'np' is not defined

In [ ]:
#특정 axis가 없으면 전체를 대상
a.sum() ,np.sum(a)

In [ ]:
# axis = 0 행을 기준으로
a.sum(axis=0), np.sum(a, axis=0)

In [32]:
# axis = 1, 행단위로 계산
a.sum(axis=1), np.sum(a, axis=1)

AttributeError: 'list' object has no attribute 'sum'

In [ ]:
#min
a.min(), np.min(a)

In [ ]:
a.min(axis=0), np.min(a, axis=0)

In [ ]:
a.min(axis=1), np.min(a, axis=1)

In [33]:
# max
a.max(), np.max(a)

AttributeError: 'list' object has no attribute 'max'

In [ ]:
a.max(axis=0), np.max(a, axis=0)#0열 단위로

In [ ]:
a.max(axis=1), np.max(a, axis=1)

In [ ]:
# 누적합계 : cumsum
a.cumsum(), np.cumsum(a)

In [34]:
a.cumsum(axis=0), np.cumsum(a, axis=0)

AttributeError: 'list' object has no attribute 'cumsum'

In [ ]:
a.cumsum(axis=1), np.cumsum(a, axis=1)

In [ ]:
# 평균 mean
a.mean(), np.mean(a)

In [ ]:
a.mean(axis=0), np.mean(a,axis=0)

In [35]:
a.mean(axis=1), np.mean(a,axis=1)

AttributeError: 'list' object has no attribute 'mean'

In [ ]:
#median()중앙값
np.median(a)

In [ ]:
np.median(a, axis=0) #열단위로 중앙값을 구해라

In [ ]:
np.median(a, axis=1) #행단위로 중앙값을 구해라

In [ ]:
# 상관계수
np.corrcoef(a) #전체data로 상관계수를 구해라 다 1이 나온다.


In [36]:
# 표준편차
a.std(), np.std(a)

AttributeError: 'list' object has no attribute 'std'

In [ ]:
a.std(axis=0), np.std(a,axis=0)

In [ ]:
a.std(axis=1), np.std(a,axis=1)

#### broadcasting
- 일반적으로 벡터나 행렬의 크기가 같아야 연산을 수행할 수 있다.
- 넘파이에서 서로 다른 크기를 가진 두 배열의 연산도 지원한다.

In [37]:
x = range(1, 10)
x

range(1, 10)

In [38]:
y = np.arange(1, 10)
y

NameError: name 'np' is not defined

In [ ]:
y + 3 #repeat함수를 쓰는 것과 같다.

In [ ]:
z = [1, 2, 3]

In [ ]:
y + z

In [ ]:
a = np.arange(1, 25).reshape(4,6)
pprint(a)
b = np.arange(25, 49).reshape(4, 6)
pprint(b)

In [ ]:
# shape이 같은 배열의 연산
a+b

In [ ]:
# shape이 다른 두 배열의 연산
## 두 배열을 같은 shape으로 만든 후 연산을 수행

In [39]:
# case1 : 배열과 스칼라
pprint(a)

NameError: name 'pprint' is not defined

In [ ]:
a + 100

In [ ]:
# step1. 스칼라를 배열로 변경
new_arr = np.full_like(a, 100)
new_arr

In [ ]:
# step2.배열 연산
a + new_arr

In [40]:
# case2, shape이 다른 두 배열의 연산
a = np.arange(5).reshape(1, 5)
pprint(a)
b = np.arange(5).reshape(5, 1)
pprint(b)

NameError: name 'np' is not defined

In [ ]:
a+b

#### 배열 복사

In [41]:
a = np.random.randint(0,9,(3,3))
pprint(a)

NameError: name 'np' is not defined

In [ ]:
a1 = np.copy(a)
a1[ : , 0] = 0
a1
pprint(a1)

In [ ]:
pprint(a)

### 9. 배열정렬
- axis를 기준으로 요소 정렬하는 함수 sort()

In [42]:
unsorted_arr = np.random.random((3, 3))
pprint(unsorted_arr)

NameError: name 'np' is not defined

In [ ]:
arr1 = unsorted_arr.copy()
arr2 = unsorted_arr.copy()
arr3 = unsorted_arr.copy()

In [ ]:
#axis = -1 #거꾸로
arr1.sort()
pprint(arr1)

In [43]:
# axiss = 0 열단위로 계산
arr2.sort(axis=0)
pprint(arr2)

TypeError: 'axis' is an invalid keyword argument for sort()

In [ ]:
# axis = 1 행단위로 계산
arr3.sort(axis=1)
pprint(arr3)

### 10.서브셋, 슬라이싱, 인덱싱

In [44]:
arr0 = np.arange(24) #0~23까지 1차워 배열
pprint(arr0)
arr1 = np.arange(24).reshape(4, 6)#2차원 배열
pprint(arr1)
arr2 = np.arange(24).reshape(2, 4, 3) #3차원 배열
pprint(arr2)

NameError: name 'np' is not defined

####1차원 배열의 요소 참조 및 변경

In [45]:
arr0[5] #5번째 인덱스를 참조하라

NameError: name 'arr0' is not defined

In [ ]:
arr0[5] = 10000
pprint(arr0)

####2차운 배열의 요소 참조 및 변경

In [46]:
#1행에 두번째 컬럼 요소 참조
#arr1[행, 열]
arr1[0, 1]

NameError: name 'arr1' is not defined

In [ ]:
arr1[0, 1] = 100000
pprint(arr1)

#####3차원 배열 인덱스

In [47]:
#2번째 면, 첫번째 행, 두번째 열 참조
arr2[1, 0, 1]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
arr2[1, 0, 1] = 10000
pprint(arr2)

In [ ]:
#인덱스는 특정위치의 값을 참조하고 바꾸는 것
# 슬라이싱은 시작값과 마지막값, colum 연산자 : 씀

##### 슬라이싱(slicing)
- from_index:to_index (시작위치:마지막위치-1)
- 음수 인덱스 : -1(반대방향, 마지막 인덱스를 의미)


In [48]:
pprint(arr1)

Pretty printing has been turned OFF


In [49]:
arr1 = np.arange(1,25).reshape(4, 6)#2차원 배열
pprint(arr1)

NameError: name 'np' is not defined

In [ ]:
# 가운데 요소 추출
arr1[1:3, 1:5]

In [ ]:
arr1[1:-1, 1:-1]

In [ ]:
a = arr1[:, 1:3]
pprint(a)

In [ ]:
arr[:, 1:3] = 9999
pprint(arr1)

#### 블린 인덱싱(Boolean indexing)

In [50]:
arr1 = np.arange(1,25).reshape(4, 6)#2차원 배열
pprint(arr1)

NameError: name 'np' is not defined

In [ ]:
#arr1 배열에서 요소의 값이 짝수인 요소들의 총합은?

sum(arr1[arr1 %2 ==0])

In [ ]:
arr1 % 2 == 0 #짝수를 뜻함

In [ ]:
arr1[arr1 % 2 == 0] #true인 값만 뽑아라

In [ ]:
np.sum(arr1[arr1 % 2 == 0])

#### Fancy Indexing
인덱스를 전달하는 것
인덱스를 반환하라


In [51]:
arr = np.arange(1,25).reshape(4, 6)#2차원 배열
pprint(arr)

NameError: name 'np' is not defined

In [ ]:
[arr[0,0], arr[1,1], arr[2,2], arr[3,3]]

In [ ]:
arr[[0,1,2,3],[0,1,2,3]]

In [ ]:
arr[:, [1,2]]

### 11.배열 변환Transposing Array(전치행렬 - 행과 열을 바꿔라)
- 전치, 배열 shape의 변환, 배열 요소의 추가/삭제, 배열 결합, 분리

#### 전치(Transpose): 행렬의 행과 열을 바꾼다.

In [52]:
a = np.random.randint(1, 10, (2,3))
pprint(a)

NameError: name 'np' is not defined

In [ ]:
pprint(a.T)

#### 배열 형태 변경
- ravel : 배열의 shape을 1차원 배열로 만드는 메서드
- reshape:데이터의 변경없이 지정된 shape으로 변환하는 메서드

In [53]:
a = np.random.randint(1, 10, (2,3)) #2행3열
pprint(a)

NameError: name 'np' is not defined

In [ ]:
b = a.ravel() #무조건 1차원 배열

In [ ]:
a

In [ ]:
b[0] = 99 #같은 주소를 쓰는 깊은 복사
pprint(b)

In [ ]:
pprint(a)

In [ ]:
x = [1, 2, 3, 4, 5]
x

In [ ]:
x1 = x
x1

In [54]:
x1[0] = 100
x1

NameError: name 'x1' is not defined

In [ ]:
x #주소를 공유하기 때문에 원본 데이터가 바꼈다.

In [ ]:
x2 = x[:] #x라는 배열의 시작부터 마지막값
x2 #':'이 있으면 값만 바뀐다.

In [55]:
x2[0] = 100
x2

NameError: name 'x2' is not defined

In [ ]:
x

In [ ]:
a = np.random.randint(1, 10, (2,3)) #2행3열#요소6개
pprint(a)

In [ ]:
result = a.reshape(3, 2, 1) #어쩌든둥 6만 나오면된다.
pprint(result)

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x

In [56]:
y = x.reshape(3, -1) #-1이면 무시하라
pprint(y)

AttributeError: 'range' object has no attribute 'reshape'

요소 추가/삭제
- 배열의 요소, 변경, 추가, 삽입, 삭제
- resize, append, insert, delete
- resize(크기변경)와 reshape 함수는 shape를 변경한다는 부분에서는 유사
- 단, resize는 shape을 변경하는 과정에서 배열의 요소의 수가 줄거나 늘어난다.

In [57]:
a = np.random.randint(1, 10, (2,6)) #2행3열#요소12개
pprint(a)

NameError: name 'np' is not defined

In [ ]:
#shape 변경, 요소수 변경없음=reshape
a.resize((6,2))
pprint(a)

In [ ]:
b = np.random.randint(1, 10, (2,6)) #2행3열#요소12개
pprint(b)

In [ ]:
#요소의 수를 12->20개로
#늘어난 요소는 0으로 채워진다.
b.resize((2,10))#요소의 수가 20개여야 하는데 원래12개
pprint(b)

In [ ]:
c = np.random.randint(1, 10, (2,6)) #2행3열#요소12개
pprint(c)

In [58]:
# 요소수를 12개에서 9개를 감축
# 남은 수는 삭제
c.resize((3,3))
pprint(c)

AttributeError: 'list' object has no attribute 'resize'

#### append(arr, value, axis=None)
- 배열에 끝에 추가

In [59]:
x = np.arange(1, 10).reshape(3, 3)
pprint(x)
y = np.arange(10, 19).reshape(3, 3)
pprint(y)

NameError: name 'np' is not defined

In [ ]:
# case1. axis 지정없이 추가하는 방법
#axis를 지정하지 않으면, 배열은 1차운 배열로 변형되어 결합된다.
result = np.append(x, y) #x라는 배열뒤에 y라는 배열 추가
pprint(result) #axis값을 지정하지 않았기 때문에 1차원 배열
#원본 데이터가 변경되지 않았다.

In [ ]:
pprint(x)

In [ ]:
#case2. axis = 0, 열 단위
result = np.append(x, y, axis=0) #axis가0일때는 열은 같아야 한다.
pprint(result)

In [ ]:
# case3. axis = 1, 열을 기준으로
result = np.append(x, y, axis=1)
pprint(result)

##### insert(배열, 추가할객체, 추가할 값, 축)

In [60]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

NameError: name 'np' is not defined

In [ ]:
# a라는 배열을 일차원 배열로 변환하고 1번 인덱스에 99를 추가
#axis라는 축값을 안줄 수 있다. append에서 축값을 안주면1차원으로 변형
#여기서도 axis값을 주지 않으면 1차원 배열이 된다.
np.insert(a, 1, 99)

In [ ]:
np.insert(a, 1, 99, axis=0) #1번째 행 행방향으로 추가해라

In [ ]:
np.insert(a, 1, 99, axis=1) #2번째 열에 있는 258이 한칸 밀리고 추가 됨

#### delete(배열, 대상위치, 축axis=None)
- 원본 데이터가 변하지 않는다.

In [61]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

NameError: name 'np' is not defined

In [ ]:
#1차원 배열로 변환하고 1번째 index 삭제
np.delete(a, 1)

In [ ]:
np.delete(a, 1, axis=0)

In [ ]:
np.delete(a, 1, axis=1)

#### 배열 결합
- np.concatenate((a1, a2), axis) axis = 0(기본값)
- np.vstack : 수직 방향으로 배열 결합(axis = 0)
- np.hstack : 수평 방향으로 배열 결합(axis = 1)


In [62]:
a = np.arange(1, 7).reshape(2, 3)
pprint(a)
b = np.arange(7, 13).reshape(2, 3)
pprint(b)

NameError: name 'np' is not defined

In [ ]:
result = np.concatenate((a, b)) #axis = 0
result

In [ ]:
result = np.concatenate((a, b),axis = 1) #
result

#### 수직방향 배열 결합:vstack
- np.concatenate((a, b), axis=0)와 같다.
- 결합할 데이터를 튜플로 담는다.


In [63]:
a = np.arange(1, 7).reshape(2, 3)
pprint(a)
b = np.arange(7, 13).reshape(2, 3)
pprint(b)

NameError: name 'np' is not defined

In [ ]:
np.vstack((a,b))

In [ ]:
np.vstack((a, b, a, b))

#### 수평방향 배열 결합:hstack
-np.concatenate((a, b),axis = 1) 와 동일

In [64]:
a = np.arange(1, 7).reshape(2, 3)
pprint(a)
b = np.arange(7, 13).reshape(2, 3)
pprint(b)

NameError: name 'np' is not defined

In [ ]:
np.hstack((a,b))

In [ ]:
np.hstack((a, b, a, b))

#### 배열 분리
- np.hsplit() : 수평(행-방향)으로 분할
- np.vsplit() : 수직(열-방향)으로 분할

In [65]:
a = np.arange(1, 25).reshape(4,6)
pprint(a)

NameError: name 'np' is not defined

In [ ]:
# 수평방향hsplit 배열을 두 그룹으로 분할
result = np.hsplit(a, 2)
result #3차원

In [ ]:
result = np.hsplit(a, 3)
result

In [ ]:
# 구간 설정 배열을 이용하여 여러 구간으로 구분
# a라는 배열의 첫번 째 칸만 들고오려면
## a[:, :1]이렇게 해야해, a[:,1:3], a[:,3:6]
result = np.hsplit(a, [1, 3, 6])
result

In [1]:
import numpy as np

In [11]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
y = x[5:8]
y

array([6, 7, 8])

In [13]:
y[0] = 100
y

array([100,   7,   8])

In [14]:
y[:] = 99
y #y는 x와 주소를 공유해서 만들어 졌기 때문에, 원본 x가 바뀐다.

array([99, 99, 99])

In [15]:
x #x의 값도 바뀐다. 왜? 메모리가 공유되기 때문에

array([ 1,  2,  3,  4,  5, 99, 99, 99,  9, 10])

In [16]:
z = x[:].copy #인덱스 값이 없을 대 create new space
z #z는 x의 값을 가져온거지 메모리를 가져온것 이 아니다.

<function ndarray.copy>

In [19]:
z = x.copy #인덱스 값이 없을 대 create new space
z

<function ndarray.copy>

In [20]:
z[0]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [18]:
z[0] = -100
print(z) #z인덱스로 바꼈으니 바뀐다.
print(x) #z와x는 

TypeError: 'builtin_function_or_method' object does not support item assignment

In [21]:
# axis = 0(행을 기준으로), axis=1(열을 기준으로)
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
#파이썬 내장함수'배열명.sum()'를 이용한 합계
a.sum()

45

In [23]:
#넘파이 내장함수를 이용한 합계
np.sum(a) #축이 없으면 전체 데이터를 값으로 놓고 계산

45

In [ ]:
np.sum(a, axis=0) #axis0은 행 행을 기준으로 동일한 위치에 있는 것을 계산

### Boolean Index

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [31]:
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [26]:
data

array([[-1.07380548, -0.80575215, -0.93152861,  0.68319973],
       [-0.72933073, -0.74143275,  0.25424005,  0.58878804],
       [-2.34007941,  0.67358318,  0.58052225, -0.83123212],
       [-0.70378688, -1.08413245, -0.41354351, -0.72482548],
       [-0.33771584, -0.09408327, -1.10329324, -1.213088  ],
       [ 0.89695928,  1.22460177, -0.96613769,  0.03806155],
       [-0.55175953, -1.31757869, -0.73724866, -0.74184308]])

In [27]:
data % 2 == 0 #짝수

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
data[data % 2 == 0] #대괄호안에 조건

array([], dtype=float64)

In [32]:
names == ' Bob'

array([False, False, False, False, False, False, False])

In [34]:
data[names == ' Bob']

array([], shape=(0, 4), dtype=float64)

#### 전치 행렬과 축 바꾸기
- numpy에서는 transpose()와 T

In [37]:
#일반적으로 일차원은 전치를 하게되면 내용이 변경되지 않는다.
x = np.arange(4).reshape(2, 2) #2행2열짜리 담아서
x

array([[0, 1],
       [2, 3]])

In [38]:
x.T

array([[0, 2],
       [1, 3]])

In [39]:
np.transpose(x) #(=x.T)

array([[0, 2],
       [1, 3]])

In [40]:
y = np.ones((1,2, 3)) #3차원 배열
y

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
np.transpose(y, (1, 0, 2)).shape

(2, 1, 3)